#!/bin/bash

backup_directory="backup_directory"
path=$1
archive=$2
types=$3

cd $HOME
mkdir $backup_directory
files=$(find $path -name "*.cpp")
cp $files $backup_directory
tar -cvzf $archive $backup_directory

rm -r $backup_directory
echo "Done"
