#!/bin/bash

backup_directory="backup_directory"
path=$1
archive=$2
types=$3

cd $HOME
mkdir $backup_directory 2>>ftrash
files=$(find $path -name "*.cpp")
vtrash=$(cp $files $backup_directory)
vtrash=$(tar -cvzf $archive $backup_directory)

rm ftrash
rm -r $backup_directory
echo "Done"
